# CF is an Infrastructure as Code Servie
AWSTemplateFormatVersion: "2010-09-09"
Description: Basic template used to create an S3 bucket.

# CF Template can have 6 sections

# Parameters (mutable inputs)
Parameters:
  BucketName:
    Type: String
    Description: The name of the bucket to create
  Owner:
    Type: String
    Description: Owner's username

# Mappings (immutable inputs)

# Resources (required)
MyS3Bucket:
  Type: AWS::S3::Bucket
  Description: "My sample S3 bucket"
  Properties:
    BucketName: !Ref BucketName
    Tags:
      -
        Key: name
        Value: !Ref Owner

# Conditions

# Metadata

# Outputs
Outputs:
  S3Bucket:
    Value: !Ref MyS3Bucket
    Description: S3 bucket from CF template